# Azure DevOps CI/CD Pipeline Sample
# File: azure-pipelines.yml
#
# This pipeline demonstrates:
# - Multi-stage pipeline (Build, Test, Deploy)
# - Environment approvals
# - Variable groups
# - Artifact publishing

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - '**.md'
      - 'docs/**'

pr:
  branches:
    include:
      - main

variables:
  - name: nodeVersion
    value: '20'
  - name: vmImageName
    value: 'ubuntu-latest'
  # Reference variable group from Library
  # - group: my-variable-group

stages:
  # ============================================
  # BUILD STAGE
  # ============================================
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build & Test'
        pool:
          vmImage: $(vmImageName)
        
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: $(nodeVersion)
          
          - script: npm ci
            displayName: 'Install dependencies'
          
          - script: npm run lint
            displayName: 'Run linting'
          
          - script: npm test
            displayName: 'Run tests'
          
          - script: npm run build
            displayName: 'Build application'
          
          - task: CopyFiles@2
            displayName: 'Copy files to staging'
            inputs:
              sourceFolder: 'dist'
              contents: '**'
              targetFolder: '$(Build.ArtifactStagingDirectory)'
          
          - task: PublishBuildArtifacts@1
            displayName: 'Publish artifact'
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'drop'
              publishLocation: 'Container'

  # ============================================
  # DEPLOY TO DEV STAGE
  # ============================================
  - stage: DeployDev
    displayName: 'Deploy to Dev'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeployDev
        displayName: 'Deploy to Dev Environment'
        pool:
          vmImage: $(vmImageName)
        environment: 'development'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                
                - task: AzureWebApp@1
                  displayName: 'Deploy to Azure Web App'
                  inputs:
                    azureSubscription: 'Azure-Service-Connection'
                    appType: 'webAppLinux'
                    appName: 'my-webapp-dev'
                    package: '$(Pipeline.Workspace)/drop/**/*.zip'

  # ============================================
  # DEPLOY TO STAGING STAGE
  # ============================================
  - stage: DeployStaging
    displayName: 'Deploy to Staging'
    dependsOn: DeployDev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    jobs:
      - deployment: DeployStaging
        displayName: 'Deploy to Staging Environment'
        pool:
          vmImage: $(vmImageName)
        environment: 'staging'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                
                - task: AzureWebApp@1
                  displayName: 'Deploy to Azure Web App'
                  inputs:
                    azureSubscription: 'Azure-Service-Connection'
                    appType: 'webAppLinux'
                    appName: 'my-webapp-staging'
                    package: '$(Pipeline.Workspace)/drop/**/*.zip'

  # ============================================
  # DEPLOY TO PRODUCTION STAGE
  # ============================================
  - stage: DeployProduction
    displayName: 'Deploy to Production'
    dependsOn: DeployStaging
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: DeployProduction
        displayName: 'Deploy to Production Environment'
        pool:
          vmImage: $(vmImageName)
        environment: 'production'  # Requires approval
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                
                - task: AzureWebApp@1
                  displayName: 'Deploy to Azure Web App'
                  inputs:
                    azureSubscription: 'Azure-Service-Connection'
                    appType: 'webAppLinux'
                    appName: 'my-webapp-prod'
                    package: '$(Pipeline.Workspace)/drop/**/*.zip'
                
                - script: echo "Production deployment complete!"
                  displayName: 'Deployment notification'

# ============================================
# NOTES:
# ============================================
#
# Prerequisites:
# 1. Create Service Connection:
#    - Project Settings > Service connections > New > Azure Resource Manager
#    - Name it 'Azure-Service-Connection'
#
# 2. Create Environments:
#    - Pipelines > Environments > New environment
#    - Create: development, staging, production
#    - Add approval checks for production
#
# 3. Create Variable Groups (optional):
#    - Pipelines > Library > Variable groups
#    - Add secrets and variables
#
# 4. Environment Approvals:
#    - Go to Environments > production > Approvals and checks
#    - Add required approvers