# GitHub Actions CI/CD Pipeline Sample
# File: .github/workflows/ci-cd.yml
#
# This pipeline demonstrates:
# - Build and test on push/PR
# - Deploy to Azure on main branch
# - Environment-based deployments
# - Secrets management

name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:  # Manual trigger

env:
  NODE_VERSION: '20'
  AZURE_WEBAPP_NAME: 'my-webapp'

jobs:
  # ============================================
  # BUILD & TEST JOB
  # ============================================
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint
      
      - name: Run tests
        run: npm test
      
      - name: Build application
        run: npm run build
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/
          retention-days: 7

  # ============================================
  # SECURITY SCAN JOB
  # ============================================
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run security audit
        run: npm audit --audit-level=moderate
      
      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  # ============================================
  # DEPLOY TO STAGING
  # ============================================
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [build, security]
    if: github.ref == 'refs/heads/develop'
    environment:
      name: staging
      url: https://staging.example.com
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: dist/
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure Web App (Staging)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}-staging
          package: dist/

  # ============================================
  # DEPLOY TO PRODUCTION
  # ============================================
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build, security]
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://example.com
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: dist/
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure Web App (Production)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: dist/
      
      - name: Notify on success
        if: success()
        run: echo "Deployment successful!"

# ============================================
# NOTES:
# ============================================
# 
# Required Secrets:
# - AZURE_CREDENTIALS: Azure service principal JSON
#   {
#     "clientId": "<client-id>",
#     "clientSecret": "<client-secret>",
#     "subscriptionId": "<subscription-id>",
#     "tenantId": "<tenant-id>"
#   }
#
# To create Azure credentials:
# az ad sp create-for-rbac --name "github-actions" --role contributor \
#   --scopes /subscriptions/{subscription-id} --sdk-auth
#
# Environment Protection Rules:
# - Go to Settings > Environments
# - Create 'staging' and 'production' environments
# - Add required reviewers for production